dw_42021_prj_grp3_lam/dw_42021_prj_grp3_lam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('documentaries.urls')),
    path('admin/', admin.site.urls),
    path('administration/', include('administration.urls')),
    path('usermanagement/', include("usermanagement.urls")),
    path('documentaries/', include('documentaries.urls')),
    path('message/', include('message.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dw_42021_prj_grp3_lam/message/urls.py
#Grigor Mihaylov 1937997
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('newChat', views.newChat, name='newChat')
]

dw_42021_prj_grp3_lam/message/models.py
#Grigor Mihaylov 1937997
from django.db import models
from usermanagement.models import User

from django.utils import timezone

# Create your models here.

class Chats(models.Model):
    id = models.AutoField(primary_key=True)
    members = models.ManyToManyField(User)

    def __str__(self):
        objInStr="Chat with: "
        for m in self.members:
            objInStr = objInStr + m.username +", "

        return objInStr

class Messages(models.Model):

    messageContent = models.CharField(max_length=1000)
    chat = models.ForeignKey(Chats,  on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timeStamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        objInStr= "Message from: " +self.user.username +" in "+self.chat;
        return objInStr

dw_42021_prj_grp3_lam/message/forms.py
#Grigor Mihaylov 1937997
from django import forms
from .models import Chats, Messages

class ChatForm(forms.Form):
    targetUsr = forms.CharField(label='targetUsr', max_length=32)





class MessagesCreate(forms.Form):

    messageContent = forms.CharField(max_length=1000)
    chat = forms.IntegerField()

    class Meta:
        model = Messages
        fields = ['messageContent', 'chat']

dw_42021_prj_grp3_lam/message/views.py
#Grigor Mihaylov 1937997
from django.shortcuts import render
from .forms import ChatForm, MessagesCreate
# Create your views here.
def index(request):
    request.session['user_id']= 'grigor' #TEMOPRARRY !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    context = {}
    context['author'] = 'Grigor Mihaylov (1937997)'
    auth = request.session.get('user_id', '')
    if (not auth):
        context['tabTitle'] = 'Not logged in'
        return render(request, 'message/noLogin.html', context)



    if request.method == 'POST':
        context['messageMakeForm'] = MessagesCreate()
        context['tabTitle'] = 'Chat'
        context['uname'] = 'UserName'  # TEMOPRARRY !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        data1 = range(0);  # TEMOPRARRY !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        context['testList'] = data1

        form =MessagesCreate(request.POST)
        if form.is_valid():
            data = form.cleaned_data

            return render(request, 'message/chatDisplay.html', context)
        else:
            form = ChatForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data

                return render(request, 'message/chatDisplay.html', context)

    context['chatGetForm'] = ChatForm()
    data = range(10)  # TEMOPRARRY !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    context['testList'] = data
    context['tabTitle'] = 'Messages'
    return render(request, 'message/index.html', context)






def newChat(request):
    request.session['user_id'] = 'grigor'  # TEMOPRARRY !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    context = {}
    context['author'] = 'Grigor Mihaylov (1937997)'
    auth = request.session.get('user_id', '')
    if (not auth):
        context['tabTitle'] = 'Not logged in'
        return render(request, 'message/noLogin.html', context)

    form = ChatForm(request.POST)
    if form.is_valid():
        data = form.cleaned_data

        context['chatGetForm'] = ChatForm()
        context['tabTitle'] = 'Messages'
        return render(request, 'message/index.html', context)

    data = range(20); # TEMOPRARRY !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    context['tabTitle'] = 'New Chat'
    context['testList'] = data
    context['chatMakeForm'] = ChatForm()

    return render(request, 'message/newChat.html', context)

dw_42021_prj_grp3_lam/message/templates/message/chatDisplay.html
{% extends 'super.html' %}

{% load static %}
{% block addCss %}

<link href="{% static 'messages/style.css' %}" rel="stylesheet" text="text/css"/>
{% endblock %}
{% block js %}
<script defer src="{% static 'messages/messagesScript.js' %}"></script>

{% endblock %}

{% block content %}
    <h1 class="title">Chat with {{ uname }}</h1>

    <div class="mainContainer" id="displayedChat">

            <div id="messages">

            {% if testList %}
                {% for i in testList reversed%}
                <div class="{% cycle 'ownMsg' 'ownMsg' 'othersMsg' %} ">
                    <p class="msgText">
                        <span class="timeStamp">00:00 :</span>
                        <span class="text">Msg#{{i}}
                        {% cycle 'So this is suppose to simulat e a long message wiht real words so we see if it looks wierd or if this thing yis working heheheh :P' 'Short lol' 'So this is suppose to simulat e a long message wiht real words so we see if it looks wierd or if this thing yis working heheheh :P' %}
                        </span>
                    </p>
                </div>
                {% endfor %}
            {% else %}
                <p  class="emptyListMessage">You have no messages with {{ uname }}</p>
            {% endif %}
                <div class="ownMsg" id="template">
                    <p class="msgText">
                        <span class="timeStamp">00:00 :</span>
                        <span class="text"></span>
                    </p>
                </div>
            </div>

            <form method="POST" enctype="multipart/form-data" id="messageInput">
                {% csrf_token %}
                {{ messageMakeForm.as_p }}

                <button type="submit" value="Submit" id="sentMsg">Sent</button>

            </form>


    </div>
    <script>
        let id = document.querySelector("#id_chat");
        id.value=0;
        id.type="hidden";

    </script>

{% endblock %}

dw_42021_prj_grp3_lam/message/templates/message/index.html
{% extends 'super.html' %}

{% load static %}
{% block addCss %}

<link href="{% static 'messages/style.css' %}" rel="stylesheet" text="text/css"/>

<link href="{% static 'messages/newChatStyle.css' %}" rel="stylesheet" text="text/css"/>
{% endblock %}
{% block js %}
<script defer src="{% static 'messages/indexScript.js' %}"></script>

{% endblock %}

{% block content %}
    <h1 class="title">Messages</h1>
    <p class="title" id="newChatLink" >
    <a  href="newChat" >Add a Chat</a>
    </p>


<div id="newChatsContainer">


        {% if testList %}
            {% for i in testList %}
            <button class="chat" >
                <p>UserName{{ i }}</p>
                <img src="{% static 'messages/images/noavatar.jpeg' %}" height="50">
            </button>
            {% endfor %}
        {% else %}
            <p  class="emptyListMessage">You have no chats</p>
        {% endif %}

    <form  method="POST" enctype="multipart/form-data">
        {% csrf_token %}

            {{ chatGetForm.as_p }}
            <p id="selectedNewChat">Go to chat with: <span id="selected"></span></p>

            <button type="submit" value="Submit" id="newChatButton" >
                Go to Chat
            </button>
    </form>
</div>

    <script>

        let targetUsr = document.querySelector("#id_targetUsr");
        targetUsr.value="x";
        targetUsr.type="hidden";
        document.querySelector("#newChatButton").disabled = true;
    </script>

{% endblock %}

dw_42021_prj_grp3_lam/message/templates/message/newChat.html
{% extends 'super.html' %}

{% load static %}
{% block addCss %}

<link href="{% static 'messages/style.css' %}" rel="stylesheet" text="text/css"/>
<link href="{% static 'messages/newChatStyle.css' %}" rel="stylesheet" text="text/css"/>

{% endblock %}
{% block js %}
<script defer src="{% static 'messages/indexScript.js' %}"></script>

{% endblock %}

{% block content %}
<h1 class="title">Add a new chat</h1>
<div id="newChatsContainer">



            {% for i in testList %}
            <button class="chat" >
                <p>UserName{{ i }}</p>
                <img src="{% static 'messages/images/noavatar.jpeg' %}" height="50">
            </button>
            {% endfor %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

            {{ chatMakeForm.as_p }}
            <p id="selectedNewChat">Start chat with: <span id="selected"></span></p>

            <button type="submit" value="Submit" id="newChatButton" >
                Add a Chat
            </button>
    </form>

</div>
<script>

        let targetUsr = document.querySelector("#id_targetUsr");
        targetUsr.value="x";
        targetUsr.type="hidden";
        document.querySelector("#newChatButton").disabled = true;

    </script>

{% endblock %}

dw_42021_prj_grp3_lam/message/templates/message/noLogin.html
{% extends 'super.html' %}

{% block content %}
    <h1 class="title">Please Login to view your messages </h1>

{% endblock %}