dw_42021_prj_grp3_lam/documentaries/urls.py
from django.urls import path

from . import views
from .views import DocumentariesList, DocumentaryDetail, DeleteDocumentary, EditDocumentary, Forbidden

urlpatterns = [
    path('', views.index, name='index'),
    path('allDocumentaries/', DocumentariesList.as_view(), name='allDocumentaries'),
    path('documentaryDetail/<int:pk>', DocumentaryDetail.as_view(), name='documentaryDetail'),
    path('addDocumentary/', views.addDocumentary, name='addDocumentary'),
    path('allDocumentaries/search/', views.searchDocumentaries, name="documentariesFilterList"),
    path('allDocumentaries/delete/<int:pk>', DeleteDocumentary.as_view(), name="deleteDocumentary"),
    path('allDocumentaries/edit/<int:pk>', EditDocumentary.as_view(), name="editDocumentary"),
    path('forbidden/', Forbidden.as_view(), name="forbidden")
]

dw_42021_prj_grp3_lam/dw_42021_prj_grp3_lam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('documentaries.urls')),
    path('admin/', admin.site.urls),
    path('administration/', include('administration.urls')),
    path('usermanagement/', include("usermanagement.urls")),
    path('documentaries/', include('documentaries.urls')),
    path('message/', include('message.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dw_42021_prj_grp3_lam/message/urls.py
#Grigor Mihaylov 1937997
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('newChat', views.newChat, name='newChat')
]

dw_42021_prj_grp3_lam/documentaries/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from django.urls import reverse
from usermanagement.models import User
from django.utils.timezone import now

# Create your models here.
class Movie(models.Model):
    EX = "Expository"
    ES = "Essayistic"
    OB = 'Observational'
    PA = "Participatory"
    RE = "Research"
    IN = "Interview"
    NONE = None
    genreList = (
        (EX, 'Expository'),
        (ES, 'Essayistic'),
        (OB, 'Observational'),
        (PA, 'Participatory'),
        (RE, 'Research'),
        (IN, 'Interview'),
        (NONE, None),
    )

    PA = 'Parent'
    CE = 'Certificate'
    statusList = (
        (PA, "Parent's Guide"),
        (CE, 'Certificate'),
        (NONE, None),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    filmMaker = models.CharField(max_length=50)
    title = models.CharField(max_length=30)
    genre = models.CharField(max_length=30, choices=genreList, default=NONE)
    keywords = models.CharField(max_length=300)
    description = models.TextField()
    url = models.URLField(max_length=500)
    year = models.IntegerField()
    status = models.CharField(max_length=30, choices=statusList, default=NONE)
    rate = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(100)])
    snapshot = models.ImageField(upload_to='snapshots')

    def __str__(self):
        return "Title: " + self.title + ", Film Maker: " + self.filmMaker + ", Genre: " + self.genre + ", Description: " + str(
            self.description)

    def get_absolute_url(self):
        return reverse('allDocumentaries')


class Comment(models.Model):
    commentText = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=now)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return "Comment: " + str(self.commentText) + ", User: " + self.user + ", Date: " + self.date + ", Movie: " + self.movie

dw_42021_prj_grp3_lam/documentaries/forms.py
from django import forms
from django.core.validators import MaxValueValidator


class DocumentaryForm(forms.Form):
    EX = "Expository"
    ES = "Essayistic"
    OB = 'Observational'
    PA = "Participatory"
    RE = "Research"
    IN = "Interview"
    NONE = None
    genreList = (
        (EX, 'Expository'),
        (ES, 'Essayistic'),
        (OB, 'Observational'),
        (PA, 'Participatory'),
        (RE, 'Research'),
        (IN, 'Interview'),
        (NONE, None),
    )

    PA = 'Parent'
    CE = 'Certificate'
    statusList = (
        (PA, "Parent's Guide"),
        (CE, 'Certificate'),
        (NONE, None),
    )
    filmMaker = forms.CharField(label="Director", max_length=100)
    title = forms.CharField(label="Title", max_length=30)
    genre = forms.ChoiceField(choices=genreList, label="Genre")
    keywords = forms.CharField(label="Keywords", max_length=300, required=False)
    description = forms.CharField(label="Description", widget=forms.Textarea)
    url = forms.URLField(label="URL", max_length=500)
    year = forms.IntegerField(label="Year Of Release")

    status = forms.ChoiceField(choices=statusList, label="Status")
    rate = forms.IntegerField(label="Rating (out of 100)", validators=[MaxValueValidator(100)])
    snapshot = forms.ImageField(label="Movie Preview", required=False)


class CommentForm(forms.Form):
    commentText = forms.CharField(label="", max_length=1000, widget=forms.Textarea(attrs={'class': 'commentText', 'placeholder': 'Write your comment here!'}))

dw_42021_prj_grp3_lam/documentaries/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, request
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, DetailView, DeleteView, UpdateView, FormView
from usermanagement.models import User
from django.utils.timezone import now

from .forms import DocumentaryForm, CommentForm
from .models import Movie, Comment

"""
class Index(TemplateView):

    template_name = "documentaries/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['tabTitle'] = "RateMyDocumentaries"
        return context
"""

def index(request):
    return render(request, 'documentaries/index.html', {'tabTitle': "RateMyDocumentaries", 'curr_user': request.session.get('curr_user', None)})


class DocumentariesList(ListView):
    model = Movie
    template_name = "documentaries/documentaries.html"
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tabTitle'] = "Documentaries Page"
        context['curr_user'] = self.request.session['curr_user']
        return context

    def get(self, request, *args, **kwargs):
        curr_user = request.session.get('curr_user', None)
        request.session['curr_user'] = curr_user
        return super().get(request, *args, **kwargs)


def searchDocumentaries(request):
    tabTitle = 'Search Result'
    if request.method == "POST":
        search = request.POST['search']
        documentariesList = Movie.objects.filter(title__icontains=search)
        return render(request, 'documentaries/search.html', {'search': search, 'documentariesList': documentariesList, 'tabTitle': tabTitle, 'curr_user': request.session['curr_user']})
    else:
        return render(request, 'documentaries/documentaries.html', {})


class DocumentaryDetail(DetailView, FormView):
    model = Movie
    template_name = "documentaries/documentaryDetail.html"
    form_class = CommentForm

    def form_valid(self, form):
        if self.request.session['curr_user'] is None:
            return HttpResponseRedirect('/usermanagement/login')
        movieId = self.kwargs['pk']
        data = form.cleaned_data
        Comment.objects.create(commentText=data['commentText'], user=User.objects.get(id=self.request.session['curr_user'].get('id')), date=now(), movie=Movie.objects.get(id=movieId))
        return HttpResponseRedirect('/documentaries/documentaryDetail/' + str(movieId))

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['tabTitle'] = "Documentary Detail"
        context['curr_user'] = self.request.session['curr_user']
        return context

    def get(self, request, *args, **kwargs):
        curr_user = request.session.get('curr_user', None)
        request.session['curr_user'] = curr_user
        return super().get(request, *args, **kwargs)


def addDocumentary(request):

    if request.session['curr_user'] is None:
        return HttpResponseRedirect('/usermanagement/login')

    tabTitle = 'Add Documentary'
    if request.method == 'POST':
        form = DocumentaryForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data

            if data["snapshot"] is None:
                #TO-DO: change user to authenticated user
                m = Movie(user=User.objects.get(id=request.session['curr_user'].get('id')), filmMaker=data['filmMaker'], title=data['title'],
                          genre=data['genre'],
                          keywords=data['keywords'], description=data['description'], url=data['url'],
                          year=data['year'], status=data['status'], rate=data['rate'], snapshot='noavatar.jpeg')

            else:
                m = Movie(user=User.objects.get(id=request.session['curr_user'].get('id')), filmMaker=data['filmMaker'], title=data['title'],
                          genre=data['genre'],
                          keywords=data['keywords'], description=data['description'], url=data['url'],
                          year=data['year'], status=data['status'], rate=data['rate'],
                          snapshot=request.FILES['snapshot'])

            m.save()

            return HttpResponseRedirect('/documentaries/allDocumentaries/')
    else:
        form = DocumentaryForm()

    return render(request, 'documentaries/addDocumentary.html', {'form': form, 'tabTitle': tabTitle, 'curr_user': request.session.get('curr_user', None)})


def commentSection(request):

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('/documentaries/documentaryDetail/<int:pk>')
    else:
        form = CommentForm()

    return render(request, 'documentaries/documentaryDetail.html')


class DeleteDocumentary(DeleteView):
    model = Movie
    template_name = "documentaries/deleteDocumentary.html"
    success_url = reverse_lazy('allDocumentaries')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['tabTitle'] = "Documentary Detail"
        context['curr_user'] = self.request.session['curr_user']
        return context

    def get(self, request, *args, **kwargs):
        curr_user = request.session.get('curr_user', None)
        request.session['curr_user'] = curr_user
        if request.session['curr_user'] is None:
            return HttpResponseRedirect('/usermanagement/login')
        if request.session['curr_user'].get("id") is not User.objects.get(movie=Movie.objects.get(id=self.kwargs['pk'])).id:
            return HttpResponseRedirect('/documentaries/forbidden')
        return super().get(request, *args, **kwargs)

class EditDocumentary(UpdateView):
    model = Movie
    template_name = "documentaries/editDocumentary.html"
    fields = ['filmMaker', 'title', 'genre', 'keywords', 'description', 'url', 'year', 'status', 'rate', 'snapshot']

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['tabTitle'] = "Documentary Detail"
        context['curr_user'] = self.request.session['curr_user']
        return context

    def get(self, request, *args, **kwargs):
        curr_user = request.session.get('curr_user', None)
        request.session['curr_user'] = curr_user
        if request.session['curr_user'] is None:
            return HttpResponseRedirect('/usermanagement/login')
        if request.session['curr_user'].get("id") is not User.objects.get(movie=Movie.objects.get(id=self.kwargs['pk'])).id:
            return HttpResponseRedirect('/documentaries/forbidden')
        return super().get(request, *args, **kwargs)

class Forbidden(TemplateView):
    template_name = "documentaries/forbidden.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['tabTitle'] = "Documentary Detail"
        context['curr_user'] = self.request.session['curr_user']
        return context

    def get(self, request, *args, **kwargs):
        curr_user = request.session.get('curr_user', None)
        request.session['curr_user'] = curr_user
        return super().get(request, *args, **kwargs)

dw_42021_prj_grp3_lam/documentaries/templates/documentaries/addDocumentary.html
{% extends 'documentaries/index.html' %}

{% block content %}
    <h1 class="title"> Add Documentary</h1>
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" value="Submit">Add Documentary</button>
    <button> <a href="/documentaries/allDocumentaries">Return to Documentaries</a></button>
    </form>
{% endblock %}

dw_42021_prj_grp3_lam/documentaries/templates/documentaries/deleteDocumentary.html
{% extends 'documentaries/index.html' %}

{% block content %}
    <h1 class="title">Delete Documentary: {{ movie.title }}</h1>
    <button class="documentaries"><a href="/documentaries/allDocumentaries">Return To Documentaries</a></button>
    <div class="movieContainer">
        <form method=POST>
            {% csrf_token %}
            <p> <strong>Are you sure you want to delete this Documentary?</strong></p>
            <button>Confirm</button>
        </form>
    </div>
{% endblock %}

dw_42021_prj_grp3_lam/documentaries/templates/documentaries/documentaries.html
{% extends 'documentaries/index.html' %}

{% block content %}
<h1 class="title">List of Documentaries</h1>
<div class="documentaries">
    <button><a href="/documentaries/addDocumentary/">Add a New Documentary</a></button>
    <form class="search" method=POST action="{% url 'documentariesFilterList' %}">
        {% csrf_token %}
        <input class="searchInput" type="search" placeholder="Search by name..." name="search">
        <button class="searchButton" type="submit">Search</button>
    </form>
</div>
{% for obj in object_list %}
<div class="movieContainer">
    <img class="imagePreview" src="/media/{{ obj.snapshot }}">
    <h2> Documentary: {{ obj.title }}</h2>
    <p> Film Maker: {{ obj.filmMaker }}</p>
    <p> Keywords: {{ obj.keywords }}</p>
    <p> Submitted by: {{ obj.user.username }}</p>
    <button><a href="{% url 'documentaryDetail' pk=obj.id %}">Details</a></button>
    <button><a href="{% url 'deleteDocumentary' pk=obj.id %}">Delete</a></button>
    <button><a href="{% url 'editDocumentary' pk=obj.id %}">Edit</a></button>
</div> <!-- TODO: Add Delete Button -->
{% endfor %}
<div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
</div>
{% endblock %}

dw_42021_prj_grp3_lam/documentaries/templates/documentaries/documentaryDetail.html
{% extends 'documentaries/index.html' %}

{% block content %}
    <div class="movieContainer">
        <h1 class="titleDetail"> <a href="https://{{ object.url }}">{{ object.title }}</a></h1>
        <p id="description"> {{ object.description }}</p>
        <p> <b>Director:</b> {{ object.filmMaker }}</p>
        <img class="imagePreview" src="/media/{{ object.snapshot }}">
        <p> <b>Genre:</b> {{ object.genre }}</p>
        <p> <b>Keywords:</b> {{ object.keywords }}</p>
        <p> <b>Year:</b> {{ object.year }} </p>
        <p> <b>Status:</b> {{ object.status }}</p>
        <p> <b>Rating: </b> {{ object.rate }}/100</p>
        <p> <b>Submitted by:</b> {{ object.user.username }}</p>
    </div>
    <button class="documentaries"> <a href="/documentaries/allDocumentaries">Return to Documentaries</a></button>

    <div class="commentSection">
        <p> Do you have a comment? Leave them here!</p>
        <form method=POST enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" value="Comment">Comment</button>
        </form>
        {% for comment in object.comment_set.all %}
            <div class="comment">
                <strong>{{ comment.user.username }} - {{ comment.date }}</strong>
                <br>
                <br>
                {{ comment.commentText }}
            </div>
        {% endfor %}

    </div>
{% endblock %}

dw_42021_prj_grp3_lam/documentaries/templates/documentaries/editDocumentary.html
{% extends 'documentaries/index.html' %}

{% block content %}
    <h1 class="title">Edit Documentary: {{ movie.title }}</h1>
    <button class="documentaries"><a href="/documentaries/allDocumentaries">Return to Documentaries</a></button>
    <div class="movieContainer">
        <form method=POST>
            {% csrf_token %}
            {{ form.as_p }}
            <button>Confirm</button>
        </form>
    </div>
{% endblock %}

dw_42021_prj_grp3_lam/documentaries/templates/documentaries/forbidden.html
{% extends 'documentaries/index.html' %}

{% block content %}
    <h1 class="title"> You are not allowed to modify this documentary</h1>
    <button id="centerButton"> <a href="/documentaries/allDocumentaries">Return to Documentaries</a></button>
{% endblock %}

dw_42021_prj_grp3_lam/documentaries/templates/documentaries/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ tabTitle }}</title>
    {% load static %}
    <link href="{% static 'documentaries/style.css' %}" rel="stylesheet" text="text/css"/>
    <link rel="shortcut icon" type="image/png" href="/media/favicon.ico"/>
</head>
<body>
    <nav>
        <a href="/documentaries/">Home</a>
        <a href="/documentaries/allDocumentaries/">Documentaries</a>
        <a href="/message/">Message</a>
        <a href="/usermanagement/">Users</a>
        {% if curr_user %}
        <a href="/administration/">Administration</a>
             <div class="welcome">
                <span class="welcomeSpan">Welcome, {{ curr_user.username }}!</span>
                <a class='login' href="/usermanagement/logout">Log Out</a> <!-- TO-DO: log out page -->
            </div>
        {% else %}
            <div class="welcome">
                <span class="welcomeSpan">Welcome, Visitor!</span>
                <a class='login' href="/usermanagement/login/">Log in</a>
            </div>
        {% endif %}
    </nav>
    {% block content %}
        <h1 class="title">RateMyDocumentaries</h1>
        <p class="textContent"> Welcome to RateMyDocumentaries! This is a website where you can view and rate documentaries by leaving a rating or comment on our database of documentaries movies! We hope you enjoy your stay!</p>
        <p class="textContent">Page created by Daniel Lam (1932789).</p>
    {% endblock %}
    <footer>

        <p> &copy; Created by Daniel Lam (1932789). All rights reserved. </p>

    </footer>
</body>
</html>

dw_42021_prj_grp3_lam/documentaries/templates/documentaries/search.html
{% extends 'documentaries/index.html' %}

{% block content %}
    {% if search %}
        <h1 class="title">You searched for {{ search }}</h1>
        <div class="documentaries">
            <button><a href="/documentaries/allDocumentaries/">Return the Documentaries</a></button>
        </div>
        {% for obj in documentariesList %}
            <div class="movieContainer">
                <img class="imagePreview" src="/media/{{ obj.snapshot }}">
                <h2> Documentary: {{ obj.title }}</h2>
                <p> Film Maker: {{ obj.filmMaker }}</p>
                <p> Genre: {{ obj.genre }}</p>
                <button><a href="{% url 'documentaryDetail' obj.id %}">Details</a></button>
                <button><a href="{% url 'deleteDocumentary' obj.id %}">Delete</a></button>
                <button><a href="{% url 'editDocumentary' obj.id %}">Edit</a></button>
            </div>
        {% endfor %}
    {% else %}
        <h1 class="title">Empty search</h1>
        <div class="documentaries">
            <button><a href="/documentaries/allDocumentaries/">Return the Documentaries</a></button>
        </div>
    {% endif %}

{% endblock %}